# utils/modules/setting_metrics.py

# Root + sidebar + content
SETTING_ROOT_MARGINS = (0, 0, 0, 0)
SETTING_ROOT_SPACING = 0

SETTING_SIDEBAR_WIDTH = 240
SETTING_SIDEBAR_MARGINS = (16, 16, 16, 16)
SETTING_SIDEBAR_SPACING = 8

SETTING_CONTENT_MARGINS = (16, 16, 16, 16)
SETTING_CONTENT_SPACING = 8

SETTING_SAVE_BUTTON_HEIGHT = 32


# Form umum
SETTING_FORM_MARGINS = (8, 16, 16, 16)
SETTING_FORM_VERTICAL_SPACING = 8
SETTING_FORM_HORIZONTAL_SPACING = 8


# Format & Penomoran
SETTING_SUFFIX_MAX_WIDTH = 160
SETTING_RESI_MODE_MAX_WIDTH = 180


# Rekening bank
SETTING_ACCOUNT_GROUP_MARGINS = (8, 8, 8, 8)
SETTING_ACCOUNT_GROUP_SPACING = 8
SETTING_ACCOUNT_INPUT_SPACING = 4

SETTING_BANK_FIELD_WIDTH = 100
SETTING_ACCOUNT_NUMBER_WIDTH = 160
SETTING_ACCOUNT_ACTION_WIDTH = 40
SETTING_ACCOUNT_TABLE_MIN_HEIGHT = 120


# Kantor cabang
SETTING_BRANCH_GROUP_MARGINS = (16, 22, 16, 16)
SETTING_BRANCH_GROUP_SPACING = 8

SETTING_BRANCH_CODE_WIDTH = 64
SETTING_BRANCH_PREFIX_WIDTH = 96
