# themes/colors.py

"""Sumber warna global tema terang dan gelap aplikasi."""


THEME_COLORS = {
    "light": {
        "palette": {
            "window": "#f8fafc",
            "window_text": "#0f172a",
            "base": "#ffffff",
            "alternate_base": "#f1f5f9",
            "tooltip_base": "#ffffff",
            "tooltip_text": "#0f172a",
            "text": "#0f172a",
            "placeholder_text": "#cbd5e1",
            "button": "#e2e8f0",
            "button_text": "#0f172a",
            "bright_text": "#000000",
            "link": "#2563eb",
            "highlight": "#2563eb",
            "highlighted_text": "#ffffff",
            "light": "#ffffff",
            "midlight": "#e2e8f0",
            "mid": "#94a3b8",
            "dark": "#64748b",
            "shadow": "#334155",
            "disabled_text": "#94a3b8",
        },
        "ui": {
            "main_background": "#f8fafc",
            "text_primary": "#0f172a",
            "text_body": "#0f172a",
            "text_muted": "#64748b",
            "text_disabled": "#94a3b8",
            "accent": "#2563eb",
            "primary": "#2563eb",
            "primary_hover": "#1d4ed8",
            "primary_pressed": "#1e40af",
            "on_primary": "#ffffff",
            "placeholder_text": "#cbd5e1",
            "field_background": "#ffffff",
            "field_focus_background": "#ffffff",
            "field_border": "#cbd5e1",
            "panel_background": "#f8fafc",
            "panel_border": "#e2e8f0",
            "locked_background": "#f1f5f9",
            "locked_text": "#64748b",
            "locked_border": "#cbd5e1",
            "table_background": "#ffffff",
            "table_alternate_background": "#fafbfc",
            "table_text": "#0f172a",
            "table_grid": "#e2e8f0",
            "table_header_background": "#243752",
            "selection_background": "#2563eb",
            "selection_text": "#ffffff",
        },
        "buku_gudang": {
            "status": {
                "PERJALANAN": {
                    "row_background": "#EBF3FA",
                    "row_alternate_background": "#DDEAF6",
                    "text_color": "#174A7E",
                },
                "SELESAI": {
                    "row_background": "#E8F5E9",
                    "row_alternate_background": "#DDF0DF",
                    "text_color": "#1B5E20",
                },
                "MACET": {
                    "row_background": "#FDECEC",
                    "row_alternate_background": "#F8DFE2",
                    "text_color": "#8F1D27",
                },
            },
        },
    },
    "dark": {
        "palette": {
            "window": "#1a1d24",
            "window_text": "#f8fafc",
            "base": "#1a1d24",
            "alternate_base": "#20242b",
            "tooltip_base": "#0f172a",
            "tooltip_text": "#f8fafc",
            "text": "#f8fafc",
            "placeholder_text": "#4c525e",
            "button": "#1e222b",
            "button_text": "#f8fafc",
            "bright_text": "#ffffff",
            "link": "#60a5fa",
            "highlight": "#3b82f6",
            "highlighted_text": "#ffffff",
            "light": "#475569",
            "midlight": "#3f434d",
            "mid": "#4c525e",
            "dark": "#64748b",
            "shadow": "#0f172a",
            "disabled_text": "#94a3b8",
        },
        "ui": {
            "main_background": "#202124",
            "text_primary": "#ffffff",
            "text_body": "#f8fafc",
            "text_muted": "#94a3b8",
            "text_disabled": "#94a3b8",
            "accent": "#60a5fa",
            "primary": "#3b82f6",
            "primary_hover": "#2563eb",
            "primary_pressed": "#1d4ed8",
            "on_primary": "#ffffff",
            "placeholder_text": "#4c525e",
            "field_background": "#1d2024",
            "field_focus_background": "#20242b",
            "field_border": "#4c525e",
            "panel_background": "#1e293b",
            "panel_border": "#334155",
            "locked_background": "#1e293b",
            "locked_text": "#94a3b8",
            "locked_border": "#475569",
            "table_background": "#1a1d24",
            "table_alternate_background": "#20242b",
            "table_text": "#f8fafc",
            "table_grid": "#334155",
            "table_header_background": "#1e293b",
            "selection_background": "#3b82f6",
            "selection_text": "#ffffff",
        },
        "buku_gudang": {
            "status": {
                "PERJALANAN": {
                    "row_background": "#17324D",
                    "row_alternate_background": "#142C44",
                    "text_color": "#D6EAFF",
                },
                "SELESAI": {
                    "row_background": "#173B2A",
                    "row_alternate_background": "#143425",
                    "text_color": "#D7F7DF",
                },
                "MACET": {
                    "row_background": "#4A2327",
                    "row_alternate_background": "#402025",
                    "text_color": "#FFD9DD",
                },
            },
        },
    },
}


def get_theme_colors(is_dark: bool) -> dict:
    """Mengambil kumpulan warna berdasarkan tema aktif."""
    return THEME_COLORS["dark" if is_dark else "light"]